version: 2.1

executors:
  macos-executor:
    macos:
      xcode: 14.2.0

jobs:
  build_ios:
    executor: macos-executor
    steps:
      - checkout

      - run:
          name: Instalar Node.js v22 con nvm
          command: |
            echo "Listando archivos antes de la instalación de Node.js..."
            ls -aR

            echo "Instalando nvm y Node.js v22..."
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
            
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" 
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

            nvm install 22
            nvm use 22

            echo "Verificando versiones de Node.js y npm..."
            node -v
            npm -v

            echo "Listando archivos después de la instalación de Node.js..."
            ls -aR

      - run:
          name: Instalar dependencias del proyecto y de Capacitor
          command: npm install

      - run:
          name: Inicializar Capacitor, añadir plataforma iOS y configurar Cocoapods
          command: |
            echo "Inicializando Capacitor y añadiendo plataforma iOS..."
            npx cap init "NombreDeTuApp" "com.tudominio.app" --web-dir dist/spa

            npx cap add ios

            echo "Listando el contenido del proyecto después de añadir la plataforma iOS..."
            ls -aR

            echo "Navegando al directorio de iOS e instalando Cocoapods..."
            # Asegúrate de que esta ruta sea la correcta para tu proyecto
            cd ios
            pod install
            
            echo "Cocoapods ha terminado. Listando archivos en el directorio de iOS..."
            ls -aR

      - run:
          name: Compilar proyecto Quasar
          command: npx quasar build

      - run:
          name: Copiar build de Quasar a Capacitor
          command: npx cap sync

      - run:
          name: Compilar y archivar proyecto iOS
          command: |
            xcodebuild clean archive \
            -workspace ios/App.xcworkspace \
            -scheme App \
            -configuration Release \
            -archivePath build/App.xcarchive \
            -destination generic/platform=iOS

      - run:
          name: Exportar .ipa
          command: |
            xcodebuild -exportArchive \
            -archivePath build/App.xcarchive \
            -exportPath build/ipa \
            -exportOptionsPlist exportOptions.plist

      - persist_to_workspace:
          root: .
          paths:
            - build/ipa

workflows:
  build_app:
    jobs:
      - build_ios