version: 2.1

jobs:
  build-ios:
    macos:
      xcode: 15.4.0
    steps:
      - checkout
      - run:
          name: Add iOS Platform
          command: npx cap add ios
      - run:
          name: Build iOS Project
          command: |
            cd ios/App
            xcodebuild -workspace App.xcworkspace -scheme App -configuration Release -sdk iphoneos -archivePath $PWD/build/App.xcarchive archive
            xcodebuild -exportArchive -archivePath $PWD/build/App.xcarchive -exportOptionsPlist exportOptions.plist -exportPath $PWD/build

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-ios