version: 2.1
orbs:
  node: circleci/node@5.0.3

jobs:
  build_and_test:
    executor:
      name: node/default
      tag: '16.14.0' # Puedes cambiar esta versión por la que necesites
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Build
          command: npm run build
      - run:
          name: Test
          command: npm test

workflows:
  build_and_test_workflow:
    jobs:
      - build_and_test:
          filters:
            branches:
              only:
                - main # Este job solo se ejecutará en la rama 'main'
