version: 2.1

executors:
  macos-executor:
    macos:
      xcode: 14.2.0

jobs:
  build_ios:
    executor: macos-executor
    steps:
      - checkout

      - run:
          name: Setup Node.js v22 via nvm
          command: |
            echo "Installing nvm and Node.js v22..."
            # Descarga e instala nvm
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
            
            # Carga nvm en el shell
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # Esto carga nvm
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" # Esto carga el autocompletado de bash

            # Instala y usa Node.js v22
            nvm install 22
            nvm use 22

            echo "Node.js $(node -v) y npm $(npm -v) instalados."

      - run:
          name: Install Project Dependencies
          command: npm install

      - run:
          name: Initialize Capacitor, Add iOS Platform & Install Cocoapods
          command: |
            echo "Inicializando Capacitor y añadiendo plataforma iOS..."
            # Asegúrate de que los valores de appName y appId sean correctos para tu proyecto
            npx cap init "MyQuasarApp" "com.mycompany.myquasarapp" --web-dir dist/spa
            npx cap add ios

            echo "Listando el contenido del directorio después de añadir la plataforma iOS para depuración..."
            ls -aR . # Lista desde la raíz del proyecto

            echo "Navegando al directorio de iOS para instalar Cocoapods..."
            # Ajusta esta ruta si tu carpeta iOS no está directamente en la raíz (ej. src-capacitor/ios)
            cd ios 
            pod install
            echo "Cocoapods instalado. Listando contenido del directorio iOS..."
            ls -aR .

      - run:
          name: Build Quasar Project
          command: npx quasar build

      - run:
          name: Sync Quasar Build to Capacitor
          command: npx cap sync

      - run:
          name: Archive and Build iOS Project
          command: |
            echo "Archivando y compilando el proyecto iOS..."
            # Asegúrate de que el workspace path sea correcto
            # Si iOS está en la raíz: ios/App.xcworkspace
            # Si iOS está en src-capacitor: src-capacitor/ios/App.xcworkspace
            xcodebuild clean archive \
            -workspace ios/App.xcworkspace \ 
            -scheme App \
            -configuration Release \
            -archivePath build/App.xcarchive \
            -destination generic/platform=iOS

      - run:
          name: Export .ipa
          command: |
            echo "Exportando .ipa..."
            xcodebuild -exportArchive \
            -archivePath build/App.xcarchive \
            -exportPath build/ipa \
            -exportOptionsPlist exportOptions.plist

      - persist_to_workspace:
          root: .
          paths:
            - build/ipa

workflows:
  build_app:
    jobs:
      - build_ios