version: 2.1

jobs:
  build-ios:
    macos:
      xcode: 15.4.0
    steps:
      - checkout
      - run:
          name: Add iOS Platform
          command: npx cap add ios

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-ios