version: 2.1
orbs:
  node: circleci/node@5.0.3

jobs:
  build_and_test:
    executor:
      name: node/default
      # Aquí está el cambio. Usa la versión que tú tienes.
      tag: '22.14.0'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Build
          command: npm run build
      - run:
          name: Test
          command: npm test

workflows:
  build_and_test_workflow:
    jobs:
      - build_and_test:
          filters:
            branches:
              only:
                - main
