version: 2.1

executors:
  macos-executor:
    macos:
      xcode: 14.2.0

jobs:
  build_ios:
    executor: macos-executor
    steps:
      - checkout

      - run:
          name: Instalar Node.js v22 con nvm
          command: |
            echo "Instalando nvm y Node.js v22..."
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
            . ~/.nvm/nvm.sh
            nvm install 22
            nvm use 22

      - run:
          name: Instalar dependencias del proyecto
          command: npm install

      - run:
          name: Añadir plataforma iOS
          command: npx cap add ios

      - run:
          name: Compilar proyecto Quasar
          command: npx quasar build

      - run:
          name: Copiar build de Quasar a Capacitor
          command: npx cap sync

      - run:
          name: Instalar Cocoapods
          command: |
            cd ios
            pod install

      - run:
          name: Compilar y archivar proyecto iOS
          command: |
            xcodebuild clean archive \
            -workspace ios/App.xcworkspace \
            -scheme App \
            -configuration Release \
            -archivePath build/App.xcarchive \
            -destination generic/platform=iOS

      - run:
          name: Exportar .ipa
          command: |
            xcodebuild -exportArchive \
            -archivePath build/App.xcarchive \
            -exportPath build/ipa \
            -exportOptionsPlist exportOptions.plist

      - persist_to_workspace:
          root: .
          paths:
            - build/ipa

workflows:
  build_app:
    jobs:
      - build_ios