version: 2.1

executors:
  macos-executor:
    macos:
      xcode: 14.3.1  # Puedes especificar una versión de Xcode. Elige la que mejor se adapte a tu proyecto.
    resource_class: large  # Se recomienda 'large' para compilaciones de iOS.

jobs:
  build_ios:
    executor: macos-executor
    steps:
      - checkout

      - run:
          name: Set up Node.js
          command: |
            echo "Setting up Node.js"
            nvm install 18  # Usa nvm para instalar Node.js
            nvm use 18
            npm install -g yarn # Opcional: Instalar yarn si lo usas

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Add iOS platform to project
          command: npx cap add ios

      - run:
          name: Build Quasar project
          command: npx quasar build

      - run:
          name: Copy Quasar build to Capacitor
          command: npx cap sync ios

      - run:
          name: Install Cocoapods
          command: |
            cd ios
            pod install

      - run:
          name: Build and archive iOS project
          command: |
            xcodebuild clean archive \
            -workspace ios/App.xcworkspace \
            -scheme App \
            -configuration Release \
            -archivePath build/App.xcarchive \
            -destination generic/platform=iOS \
            CODE_SIGN_STYLE="Manual" \
            CODE_SIGN_IDENTITY="Apple Distribution: Nombre de tu Empresa (XXXXX)" \
            PROVISIONING_PROFILE_SPECIFIER="Nombre del Perfil de Provisionamiento"

      - run:
          name: Export .ipa
          command: |
            xcodebuild -exportArchive \
            -archivePath build/App.xcarchive \
            -exportPath build/ipa \
            -exportOptionsPlist exportOptions.plist

      - persist_to_workspace:
          root: .
          paths:
            - build/ipa

workflows:
  build_app:
    jobs:
      - build_ios
